### ISSUE TITLE
I want fix the wind speed range in rose plot

### ISSUE THREAD

**Issue by satya0210** [JohnVolk/Rosely#5]
please see the attached images
 I want to compare the 2 plots but the wind speed that is shown in the legend is different
ax,set_ylim is not working

here is my code

from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
from numpy.random import random
from numpy import arange
import pandas as pd
MON=pd.read_csv(r'data.csv')
ws = MON["Ws"].values
wd = MON["Wd"].values
ax = WindroseAxes.from_ax()
ax.set_ylim(0,50)
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_title('plot2')
ax.set_legend()

![plot1](https://github.com/JohnVolk/Rosely/assets/100069922/a170aaa6-8068-411f-a46b-e87242798653)
![plot2](https://github.com/JohnVolk/Rosely/assets/100069922/d632df3c-f10a-480f-9ae2-7091c43f206e)

**Comment by JohnVolk** [comment]
Hi, it appears that the example you gave is using code from a different Python module, for example, there is no ``WindroseAxes`` object in this package. Also, your question is referring to ``matplotlib`` functionality.
